[build]
  command = "pnpm build"
  publish = "apps/unified/.next"

[build.environment]
  NPM_FLAGS = "--prefix=/dev/null"
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production]
  command = "pnpm build"

[context.deploy-preview]
  command = "pnpm build"

[context.branch-deploy]
  command = "pnpm build"