# DELA×PM統合システム - Netlify設定（ルートディレクトリ）

[build]
  command = "pnpm install && pnpm build:unified"
  publish = "apps/unified/.next"

[build.environment]
  NODE_VERSION = "18"

# Environment variables should be set in Netlify UI:
# NEXT_PUBLIC_SUPABASE_URL=https://pfrzcteapmwufnovmmfc.supabase.co
# NEXT_PUBLIC_SUPABASE_ANON_KEY=your_supabase_anon_key
# NEXT_PUBLIC_APP_NAME=DELA×PM統合システム
# NEXT_PUBLIC_ENABLE_PLATTO=true
# NEXT_PUBLIC_ENABLE_LIBERARY=true