# DELA×PM統合システム - Netlify設定（ルートディレクトリ）

[build]
  command = "pnpm install && pnpm build:unified"
  publish = "apps/unified/out"
  base = "."

[build.environment]
  NODE_VERSION = "20"
  # TailwindCSSとturboのために本番環境でも必要な依存関係を含める
  NPM_FLAGS = "--production=false"

# Environment variables should be set in Netlify UI:
# NEXT_PUBLIC_SUPABASE_URL=https://pfrzcteapmwufnovmmfc.supabase.co
# NEXT_PUBLIC_SUPABASE_ANON_KEY=your_supabase_anon_key
# NEXT_PUBLIC_APP_NAME=DELA×PM統合システム
# NEXT_PUBLIC_ENABLE_PLATTO=true
# NEXT_PUBLIC_ENABLE_LIBERARY=true
# NEXT_PUBLIC_ENABLE_GUEST_ACCESS=true

# Weekly Review Edge Function Environment Variables (set in Supabase Dashboard):
# SLACK_WEBHOOK_URL=your_slack_webhook_url
# REVIEW_EMAIL=h.kodera@gmail.com
# APP_BASE_URL=https://delaxpm.netlify.app
# RESEND_API_KEY=your_resend_api_key

# リダイレクトルール
[[redirects]]
  from = "/liberary-team"
  to = "/liberary"
  status = 301

[[redirects]]
  from = "/platto-team"
  to = "/platto"
  status = 301

# チーム専用URL（短縮URL）
[[redirects]]
  from = "/lib"
  to = "/liberary"
  status = 301

[[redirects]]
  from = "/pla"
  to = "/platto"
  status = 301

# 旧team URLからのリダイレクト
[[redirects]]
  from = "/team/liberary"
  to = "/liberary"
  status = 301

[[redirects]]
  from = "/team/platto"
  to = "/platto"
  status = 301