[build]
  base = "../.."
  command = "pnpm build:unified"
  publish = "apps/unified/.next"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--prefer-offline --no-audit"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  node_bundler = "esbuild"

# Environment variables (set in Netlify UI)
# NEXT_PUBLIC_SUPABASE_URL=https://pfrzcteapmwufnovmmfc.supabase.co
# NEXT_PUBLIC_SUPABASE_ANON_KEY=your_supabase_anon_key
# NEXT_PUBLIC_APP_NAME=DELA×PM統合システム
# NEXT_PUBLIC_ENABLE_PLATTO=true
# NEXT_PUBLIC_ENABLE_LIBERARY=true